### PR TITLE
Add quotes to file path in line macros

### PR DESCRIPTION
**Pull request by billw2012**

### CODE REVIEW

**Comment by X39** [comment]
Cannot merge as this will break sqf, assembly and Config parsers. (as the paths then contain the quotes)

**Comment by billw2012** [comment]
Not sure what you mean, this only changed `#line` macros as output into pre-processed file, are you saying something else is reading those `#line` macros and expects them to not have quotes?

**Comment by X39** [comment]
https://github.com/SQFvm/vm/blob/master/src/parsing/parseassembly.cpp#L43-L64
https://github.com/SQFvm/vm/blob/master/src/parsing/parseconfig.cpp#L37-L57
https://github.com/SQFvm/vm/blob/master/src/parsing/parsesqf.cpp#L39-L59

the code snippets provided are handling the `#line` macro.
they need to be adjusted to allow this to be merged

**Comment by billw2012** [comment]
Closing in favour of #105

**Pull request closed without merging**
